import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const locales = ['en', 'es'];
 
export function generateStaticParams() {
  return locales.map((locale) => ({locale}));
}

type LayoutProps = {
  children: React.ReactNode
  params: {
    lng: string
  }
}

export default function RootLayout({
  children, params: { lng }
}: LayoutProps) {
  
  return (
    <html lang={lng}>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
